import { RecipeInput } from "@/lib/types";

export type CatalogRecipe = RecipeInput & { id: string };

// Grouped for the filter chips in the Discover tab. A recipe's own `tags`
// array draws from this vocabulary (protein/type, cooking method, cuisine)
// so filtering by any of them just checks tag membership.
export const DISCOVER_FILTER_GROUPS: { label: string; tags: string[] }[] = [
  { label: "Type", tags: ["Chicken", "Beef", "Pork", "Seafood", "Vegetarian", "Pasta", "Soup", "Tacos"] },
  { label: "Method", tags: ["One-Pot", "Sheet-Pan", "Slow-Cooker", "Stir-Fry", "Grill"] },
  { label: "Cuisine", tags: ["Italian", "Mexican", "Asian", "Mediterranean", "American", "Indian"] },
];

export const DISCOVER_RECIPES: CatalogRecipe[] = [
  // ---------------------------------------------------------------------
  // Chicken
  // ---------------------------------------------------------------------
  {
    id: "d001",
    title: "Garlic Butter Chicken Thighs",
    description: "Crispy-skinned chicken thighs in a rich garlic butter pan sauce.",
    ingredients: [
      "4 bone-in chicken thighs",
      "2 tbsp butter",
      "4 cloves garlic, minced",
      "1/2 cup chicken broth",
      "1 tsp dried thyme",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Season chicken thighs with salt and pepper.",
      "Sear skin-side down in a hot skillet over medium-high heat until crisp, about 6 minutes.",
      "Flip and cook another 6 minutes, then remove and set aside.",
      "Add butter and garlic to the pan and cook 1 minute until fragrant.",
      "Pour in broth and thyme, scraping up browned bits, then return chicken to the pan and simmer 5 minutes.",
    ],
    tags: ["Chicken", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    image_url: null,
  },
  {
    id: "d002",
    title: "Sheet-Pan Chicken Fajitas",
    description: "Sliced chicken and peppers roasted together for an easy fajita night.",
    ingredients: [
      "1.5 lbs chicken breast, sliced into strips",
      "1 red bell pepper, sliced",
      "1 green bell pepper, sliced",
      "1 onion, sliced",
      "2 tbsp olive oil",
      "1 packet fajita seasoning (or 2 tbsp chili powder blend)",
      "8 small tortillas",
    ],
    instructions: [
      "Preheat oven to 425°F.",
      "Toss chicken, peppers, and onion with olive oil and seasoning on a sheet pan.",
      "Spread in a single layer and roast 18-20 minutes, stirring halfway, until chicken is cooked through.",
      "Warm tortillas and serve the chicken and veggies with your favorite toppings.",
    ],
    tags: ["Chicken", "Sheet-Pan", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    image_url: null,
  },
  {
    id: "d003",
    title: "Honey Garlic Chicken",
    description: "Sticky-sweet skillet chicken bites ready in under 30 minutes.",
    ingredients: [
      "1.5 lbs boneless chicken thighs, cubed",
      "2 tbsp cornstarch",
      "2 tbsp vegetable oil",
      "1/4 cup honey",
      "3 tbsp soy sauce",
      "3 cloves garlic, minced",
      "1 tbsp rice vinegar",
    ],
    instructions: [
      "Toss chicken cubes with cornstarch.",
      "Heat oil in a skillet and cook chicken until golden and cooked through, about 8 minutes.",
      "Whisk honey, soy sauce, garlic, and vinegar together.",
      "Pour sauce over chicken and simmer 2-3 minutes until glossy and thickened.",
      "Serve over rice.",
    ],
    tags: ["Chicken", "Asian"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d004",
    title: "Chicken Piccata",
    description: "Pan-seared chicken cutlets in a bright lemon-caper sauce.",
    ingredients: [
      "4 chicken cutlets",
      "1/3 cup flour",
      "3 tbsp butter",
      "2 tbsp olive oil",
      "1/2 cup chicken broth",
      "1/4 cup lemon juice",
      "2 tbsp capers",
    ],
    instructions: [
      "Dredge chicken cutlets in flour, shaking off excess.",
      "Heat oil and 1 tbsp butter in a skillet and cook cutlets 3-4 minutes per side; set aside.",
      "Add broth, lemon juice, and capers to the pan and simmer 3 minutes.",
      "Whisk in remaining butter, return chicken to the pan, and spoon sauce over the top.",
    ],
    tags: ["Chicken", "Italian"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d005",
    title: "One-Pot Chicken and Rice",
    description: "A cozy, all-in-one dinner with tender chicken and seasoned rice.",
    ingredients: [
      "4 boneless chicken thighs",
      "1 cup long-grain rice",
      "2 cups chicken broth",
      "1 onion, diced",
      "2 cloves garlic, minced",
      "1 tsp paprika",
      "2 tbsp olive oil",
    ],
    instructions: [
      "Season chicken and sear in olive oil in a large pot until browned; set aside.",
      "Add onion and garlic to the pot and cook until soft.",
      "Stir in rice and paprika, then pour in broth and scrape up browned bits.",
      "Nestle chicken back into the pot, cover, and simmer 20 minutes until rice is tender.",
    ],
    tags: ["Chicken", "One-Pot", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings: 4,
    image_url: null,
  },
  {
    id: "d006",
    title: "Crispy Parmesan Chicken Cutlets",
    description: "Golden, cheesy breaded chicken cutlets the whole family will eat.",
    ingredients: [
      "4 chicken cutlets",
      "1 cup panko breadcrumbs",
      "1/2 cup grated parmesan",
      "2 eggs, beaten",
      "1/2 cup flour",
      "3 tbsp olive oil",
    ],
    instructions: [
      "Set up a dredging station: flour, beaten eggs, and panko mixed with parmesan.",
      "Coat each cutlet in flour, then egg, then the panko mixture.",
      "Heat oil in a skillet and fry cutlets 3-4 minutes per side until golden and cooked through.",
      "Drain on paper towels before serving.",
    ],
    tags: ["Chicken", "Italian"],
    prep_time_minutes: 15,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d007",
    title: "Chicken Stir-Fry with Broccoli",
    description: "A fast, colorful stir-fry with a simple savory sauce.",
    ingredients: [
      "1.5 lbs chicken breast, sliced thin",
      "4 cups broccoli florets",
      "3 tbsp soy sauce",
      "1 tbsp oyster sauce",
      "1 tbsp cornstarch",
      "2 cloves garlic, minced",
      "2 tbsp vegetable oil",
    ],
    instructions: [
      "Whisk soy sauce, oyster sauce, cornstarch, and 1/4 cup water together.",
      "Heat oil in a wok and stir-fry chicken until nearly cooked through, about 5 minutes.",
      "Add broccoli and garlic and stir-fry 3-4 minutes until crisp-tender.",
      "Pour in sauce and cook until thickened and chicken is fully cooked, about 2 minutes.",
    ],
    tags: ["Chicken", "Stir-Fry", "Asian"],
    prep_time_minutes: 15,
    cook_time_minutes: 12,
    servings: 4,
    image_url: null,
  },
  {
    id: "d008",
    title: "Baked Chicken Tenders",
    description: "Crunchy oven-baked tenders without the mess of frying.",
    ingredients: [
      "1.5 lbs chicken tenders",
      "1 cup panko breadcrumbs",
      "1 tsp garlic powder",
      "1 tsp paprika",
      "1/2 cup flour",
      "2 eggs, beaten",
      "Cooking spray",
    ],
    instructions: [
      "Preheat oven to 425°F and set a wire rack on a baking sheet.",
      "Mix panko with garlic powder and paprika.",
      "Coat tenders in flour, then egg, then the panko mixture, pressing to adhere.",
      "Arrange on the rack, spray lightly with cooking spray, and bake 18-20 minutes until golden and cooked through.",
    ],
    tags: ["Chicken", "American"],
    prep_time_minutes: 15,
    cook_time_minutes: 20,
    servings: 4,
    image_url: null,
  },
  {
    id: "d009",
    title: "Chicken Caesar Wraps",
    description: "A no-cook-required dinner using rotisserie or leftover chicken.",
    ingredients: [
      "2 cups shredded cooked chicken",
      "4 large tortillas",
      "2 cups chopped romaine",
      "1/2 cup caesar dressing",
      "1/2 cup grated parmesan",
      "1/2 cup croutons, crushed",
    ],
    instructions: [
      "Toss chicken and romaine with caesar dressing and parmesan.",
      "Divide the mixture among tortillas and top with crushed croutons.",
      "Roll up tightly, slice in half, and serve.",
    ],
    tags: ["Chicken", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    servings: 4,
    image_url: null,
  },
  {
    id: "d010",
    title: "Slow Cooker Salsa Chicken",
    description: "Three ingredients, a slow cooker, and dinner is basically done.",
    ingredients: [
      "1.5 lbs boneless chicken breasts",
      "16 oz jar salsa",
      "1 packet taco seasoning",
      "Rice or tortillas, for serving",
    ],
    instructions: [
      "Place chicken in the slow cooker and pour salsa over top; sprinkle with taco seasoning.",
      "Cover and cook on low 6 hours or high 3 hours, until chicken shreds easily.",
      "Shred chicken with two forks and stir back into the sauce.",
      "Serve over rice or in tortillas.",
    ],
    tags: ["Chicken", "Slow-Cooker", "Mexican"],
    prep_time_minutes: 5,
    cook_time_minutes: 360,
    servings: 4,
    image_url: null,
  },
  {
    id: "d011",
    title: "Lemon Herb Roasted Chicken Thighs",
    description: "Simple roasted chicken thighs brightened with lemon and herbs.",
    ingredients: [
      "8 bone-in chicken thighs",
      "1 lemon, sliced",
      "3 tbsp olive oil",
      "2 tsp dried oregano",
      "3 cloves garlic, minced",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 425°F.",
      "Toss chicken thighs with olive oil, garlic, oregano, salt, and pepper.",
      "Arrange skin-side up on a baking sheet with lemon slices tucked around them.",
      "Roast 35-40 minutes until skin is crisp and chicken is cooked through.",
    ],
    tags: ["Chicken", "Sheet-Pan", "Mediterranean"],
    prep_time_minutes: 10,
    cook_time_minutes: 40,
    servings: 4,
    image_url: null,
  },
  {
    id: "d012",
    title: "Chicken Quesadillas",
    description: "Melty cheese and seasoned chicken folded into crispy tortillas.",
    ingredients: [
      "2 cups shredded cooked chicken",
      "2 cups shredded cheddar or Mexican blend cheese",
      "8 small tortillas",
      "1 tsp cumin",
      "1 tsp chili powder",
      "Butter, for the pan",
    ],
    instructions: [
      "Toss chicken with cumin and chili powder.",
      "Layer chicken and cheese between two tortillas.",
      "Cook in a buttered skillet over medium heat 3 minutes per side until golden and cheese is melted.",
      "Slice into wedges and serve.",
    ],
    tags: ["Chicken", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d013",
    title: "Teriyaki Chicken Bowls",
    description: "Glazed chicken over rice with a sweet-savory homemade teriyaki sauce.",
    ingredients: [
      "1.5 lbs boneless chicken thighs, cubed",
      "1/3 cup soy sauce",
      "3 tbsp brown sugar",
      "1 tbsp rice vinegar",
      "1 tsp ground ginger",
      "1 tbsp cornstarch",
      "Cooked rice, for serving",
    ],
    instructions: [
      "Whisk soy sauce, brown sugar, vinegar, ginger, and cornstarch with 1/3 cup water.",
      "Cook chicken in a skillet over medium-high heat until browned, about 6 minutes.",
      "Pour in the sauce and simmer until thickened and chicken is cooked through, about 4 minutes.",
      "Serve over rice.",
    ],
    tags: ["Chicken", "Asian"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d014",
    title: "Chicken Parmesan Meatballs",
    description: "All the flavor of chicken parm in an easy meatball form.",
    ingredients: [
      "1.5 lbs ground chicken",
      "1/2 cup breadcrumbs",
      "1/4 cup grated parmesan",
      "1 egg",
      "2 cups marinara sauce",
      "1 cup shredded mozzarella",
    ],
    instructions: [
      "Preheat oven to 400°F.",
      "Mix ground chicken, breadcrumbs, parmesan, and egg; form into meatballs.",
      "Arrange in a baking dish, pour marinara over top, and bake 20 minutes.",
      "Sprinkle with mozzarella and bake 5 more minutes until melted.",
    ],
    tags: ["Chicken", "Italian"],
    prep_time_minutes: 15,
    cook_time_minutes: 25,
    servings: 4,
    image_url: null,
  },
  {
    id: "d015",
    title: "Buffalo Chicken Wraps",
    description: "Spicy shredded chicken wraps with a cooling ranch drizzle.",
    ingredients: [
      "2 cups shredded cooked chicken",
      "1/3 cup buffalo sauce",
      "4 large tortillas",
      "1 cup shredded lettuce",
      "1/2 cup ranch dressing",
      "1/2 cup shredded cheddar",
    ],
    instructions: [
      "Toss shredded chicken with buffalo sauce.",
      "Layer chicken, lettuce, cheddar, and a drizzle of ranch onto each tortilla.",
      "Roll up tightly and slice in half to serve.",
    ],
    tags: ["Chicken", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    servings: 4,
    image_url: null,
  },

  // ---------------------------------------------------------------------
  // Beef
  // ---------------------------------------------------------------------
  {
    id: "d016",
    title: "Weeknight Beef Tacos",
    description: "Classic seasoned ground beef tacos on the table in 20 minutes.",
    ingredients: [
      "1 lb ground beef",
      "1 packet taco seasoning (or 2 tbsp chili powder blend)",
      "8 small taco shells or tortillas",
      "1 cup shredded lettuce",
      "1 cup shredded cheddar",
      "1 tomato, diced",
    ],
    instructions: [
      "Brown ground beef in a skillet over medium heat, breaking it up as it cooks.",
      "Drain excess fat, add taco seasoning and 1/2 cup water, and simmer 5 minutes.",
      "Warm taco shells and fill with beef, lettuce, cheddar, and tomato.",
    ],
    tags: ["Beef", "Tacos", "Mexican"],
    prep_time_minutes: 5,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d017",
    title: "Sheet-Pan Steak Fajitas",
    description: "Juicy steak strips and peppers roasted on one pan for easy cleanup.",
    ingredients: [
      "1.5 lbs flank steak, sliced thin",
      "1 red bell pepper, sliced",
      "1 onion, sliced",
      "2 tbsp olive oil",
      "2 tbsp lime juice",
      "1 tbsp chili powder",
      "8 small tortillas",
    ],
    instructions: [
      "Preheat oven to 425°F.",
      "Toss steak, pepper, and onion with olive oil, lime juice, and chili powder on a sheet pan.",
      "Roast 12-15 minutes, stirring once, until steak reaches desired doneness.",
      "Serve with warm tortillas.",
    ],
    tags: ["Beef", "Sheet-Pan", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d018",
    title: "Beef and Broccoli Stir-Fry",
    description: "A takeout favorite made faster and fresher at home.",
    ingredients: [
      "1 lb flank steak, sliced thin",
      "4 cups broccoli florets",
      "1/3 cup soy sauce",
      "2 tbsp brown sugar",
      "1 tbsp cornstarch",
      "2 cloves garlic, minced",
      "2 tbsp vegetable oil",
    ],
    instructions: [
      "Whisk soy sauce, brown sugar, cornstarch, and 1/4 cup water together.",
      "Heat 1 tbsp oil in a wok and sear beef until browned, about 3 minutes; set aside.",
      "Add remaining oil, broccoli, and garlic and stir-fry 3-4 minutes.",
      "Return beef to the wok, pour in sauce, and cook until thickened, about 2 minutes.",
    ],
    tags: ["Beef", "Stir-Fry", "Asian"],
    prep_time_minutes: 15,
    cook_time_minutes: 12,
    servings: 4,
    image_url: null,
  },
  {
    id: "d019",
    title: "Classic Beef Chili",
    description: "A hearty, warming pot of chili that's even better the next day.",
    ingredients: [
      "1.5 lbs ground beef",
      "1 onion, diced",
      "2 cans kidney beans, drained",
      "1 can diced tomatoes",
      "2 tbsp chili powder",
      "1 tsp cumin",
      "2 cups beef broth",
    ],
    instructions: [
      "Brown ground beef with onion in a large pot; drain excess fat.",
      "Stir in chili powder and cumin and cook 1 minute.",
      "Add beans, tomatoes, and broth; bring to a simmer.",
      "Cook uncovered 25-30 minutes, stirring occasionally, until thickened.",
    ],
    tags: ["Beef", "Soup", "One-Pot", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 35,
    servings: 6,
    image_url: null,
  },
  {
    id: "d020",
    title: "One-Pot Beef Stroganoff",
    description: "Creamy, comforting stroganoff made entirely in a single pot.",
    ingredients: [
      "1 lb ground beef",
      "8 oz mushrooms, sliced",
      "1 onion, diced",
      "12 oz egg noodles",
      "3 cups beef broth",
      "1 cup sour cream",
      "2 tbsp flour",
    ],
    instructions: [
      "Brown beef with onion and mushrooms in a large pot; drain excess fat.",
      "Stir in flour and cook 1 minute, then pour in broth and noodles.",
      "Simmer 10-12 minutes, stirring occasionally, until noodles are tender.",
      "Remove from heat and stir in sour cream before serving.",
    ],
    tags: ["Beef", "One-Pot", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings: 4,
    image_url: null,
  },
  {
    id: "d021",
    title: "Skillet Salisbury Steak",
    description: "Beef patties simmered in a savory mushroom gravy.",
    ingredients: [
      "1.5 lbs ground beef",
      "1/2 cup breadcrumbs",
      "1 egg",
      "8 oz mushrooms, sliced",
      "2 cups beef broth",
      "2 tbsp flour",
      "1 onion, sliced",
    ],
    instructions: [
      "Mix ground beef, breadcrumbs, and egg; form into oval patties.",
      "Sear patties in a skillet until browned, about 4 minutes per side; set aside.",
      "Add onion and mushrooms to the pan and cook until soft.",
      "Whisk in flour, then broth, and simmer until thickened; return patties to the pan and simmer 5 minutes.",
    ],
    tags: ["Beef", "American"],
    prep_time_minutes: 15,
    cook_time_minutes: 20,
    servings: 4,
    image_url: null,
  },
  {
    id: "d022",
    title: "Beef and Bean Burritos",
    description: "Big, filling burritos loaded with seasoned beef and beans.",
    ingredients: [
      "1 lb ground beef",
      "1 can refried beans",
      "1 packet taco seasoning",
      "6 large tortillas",
      "1.5 cups shredded cheddar",
      "1 cup rice, cooked",
    ],
    instructions: [
      "Brown ground beef, drain, and stir in taco seasoning with 1/2 cup water.",
      "Warm refried beans in a small pot or the microwave.",
      "Layer beef, beans, rice, and cheese onto tortillas.",
      "Fold in the sides and roll tightly into burritos.",
    ],
    tags: ["Beef", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d023",
    title: "Slow Cooker Pot Roast",
    description: "Set it in the morning and come home to a fall-apart tender roast.",
    ingredients: [
      "3 lb chuck roast",
      "4 carrots, chopped",
      "4 potatoes, quartered",
      "1 onion, quartered",
      "2 cups beef broth",
      "1 packet onion soup mix",
    ],
    instructions: [
      "Place carrots, potatoes, and onion in the slow cooker.",
      "Set the roast on top and pour broth over everything; sprinkle with soup mix.",
      "Cover and cook on low 8 hours, until the roast shreds easily.",
      "Shred or slice the roast and serve with the vegetables.",
    ],
    tags: ["Beef", "Slow-Cooker", "American"],
    prep_time_minutes: 15,
    cook_time_minutes: 480,
    servings: 6,
    image_url: null,
  },
  {
    id: "d024",
    title: "Spaghetti with Meat Sauce",
    description: "A reliable, family-favorite red sauce with ground beef.",
    ingredients: [
      "1 lb ground beef",
      "1 jar marinara sauce",
      "1 onion, diced",
      "2 cloves garlic, minced",
      "1 lb spaghetti",
      "Grated parmesan, for serving",
    ],
    instructions: [
      "Cook spaghetti according to package directions.",
      "Brown ground beef with onion and garlic; drain excess fat.",
      "Stir in marinara and simmer 10 minutes.",
      "Serve sauce over spaghetti with grated parmesan.",
    ],
    tags: ["Beef", "Pasta", "Italian"],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    image_url: null,
  },
  {
    id: "d025",
    title: "Beef Taco Skillet",
    description: "A one-pan taco-flavored beef and rice skillet dinner.",
    ingredients: [
      "1 lb ground beef",
      "1 cup rice",
      "1 packet taco seasoning",
      "1 can diced tomatoes",
      "2 cups beef broth",
      "1 cup shredded cheddar",
    ],
    instructions: [
      "Brown ground beef in a large skillet; drain excess fat.",
      "Stir in taco seasoning, rice, tomatoes, and broth.",
      "Cover and simmer 18-20 minutes until rice is tender.",
      "Sprinkle with cheddar, cover, and let melt before serving.",
    ],
    tags: ["Beef", "One-Pot", "Mexican"],
    prep_time_minutes: 5,
    cook_time_minutes: 25,
    servings: 4,
    image_url: null,
  },
  {
    id: "d026",
    title: "Korean-Style Beef Bowls",
    description: "Sweet and savory ground beef over rice, ready in 20 minutes.",
    ingredients: [
      "1 lb ground beef",
      "1/4 cup soy sauce",
      "3 tbsp brown sugar",
      "1 tsp sesame oil",
      "2 cloves garlic, minced",
      "1 tsp ground ginger",
      "Cooked rice, for serving",
    ],
    instructions: [
      "Brown ground beef in a skillet, breaking it up as it cooks; drain excess fat.",
      "Add garlic and ginger and cook 1 minute.",
      "Stir in soy sauce, brown sugar, and sesame oil; simmer 3-4 minutes.",
      "Serve over rice, topped with green onion if desired.",
    ],
    tags: ["Beef", "Asian"],
    prep_time_minutes: 5,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d027",
    title: "Cheeseburger Sliders",
    description: "Mini cheeseburgers baked together, perfect for a quick family dinner.",
    ingredients: [
      "1 lb ground beef",
      "12 slider buns",
      "6 slices cheddar cheese",
      "2 tbsp butter, melted",
      "1 tsp garlic powder",
      "1 tsp onion powder",
    ],
    instructions: [
      "Preheat oven to 350°F.",
      "Season ground beef with garlic and onion powder and press into a thin, bun-sized patty (or individual patties).",
      "Cook patties in a skillet until browned through, then top with cheese.",
      "Assemble on slider buns, brush tops with melted butter, and bake 5 minutes until warmed through.",
    ],
    tags: ["Beef", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },

  // ---------------------------------------------------------------------
  // Pork
  // ---------------------------------------------------------------------
  {
    id: "d028",
    title: "Honey Garlic Pork Chops",
    description: "Seared pork chops finished in a sticky honey-garlic glaze.",
    ingredients: [
      "4 boneless pork chops",
      "1/4 cup honey",
      "3 tbsp soy sauce",
      "3 cloves garlic, minced",
      "1 tbsp olive oil",
      "1 tbsp apple cider vinegar",
    ],
    instructions: [
      "Season pork chops with salt and pepper and sear in olive oil, 4 minutes per side; set aside.",
      "Whisk honey, soy sauce, garlic, and vinegar together and pour into the pan.",
      "Simmer 2 minutes until slightly thickened.",
      "Return chops to the pan and spoon sauce over them before serving.",
    ],
    tags: ["Pork", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d029",
    title: "Sheet-Pan Sausage and Peppers",
    description: "Smoky sausage and sweet peppers roasted together on one pan.",
    ingredients: [
      "1.5 lbs Italian sausage links",
      "2 bell peppers, sliced",
      "1 onion, sliced",
      "2 tbsp olive oil",
      "1 tsp Italian seasoning",
      "4 hoagie rolls (optional)",
    ],
    instructions: [
      "Preheat oven to 425°F.",
      "Toss sausage, peppers, and onion with olive oil and Italian seasoning on a sheet pan.",
      "Roast 25-30 minutes, turning sausages halfway, until cooked through.",
      "Serve as-is or piled into hoagie rolls.",
    ],
    tags: ["Pork", "Sheet-Pan", "Italian"],
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings: 4,
    image_url: null,
  },
  {
    id: "d030",
    title: "Slow Cooker Pulled Pork",
    description: "Fall-apart tender pulled pork with barely any hands-on time.",
    ingredients: [
      "3 lb pork shoulder",
      "1 cup barbecue sauce, plus more for serving",
      "1/2 cup chicken broth",
      "1 tbsp brown sugar",
      "1 tsp smoked paprika",
      "Buns, for serving",
    ],
    instructions: [
      "Season pork shoulder with brown sugar and smoked paprika.",
      "Place in the slow cooker with broth and 1/2 cup barbecue sauce.",
      "Cover and cook on low 8 hours until it shreds easily.",
      "Shred the pork, toss with remaining barbecue sauce, and serve on buns.",
    ],
    tags: ["Pork", "Slow-Cooker", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 480,
    servings: 6,
    image_url: null,
  },
  {
    id: "d031",
    title: "Pork Fried Rice",
    description: "A great way to use leftover pork and rice for a fast dinner.",
    ingredients: [
      "2 cups cooked pork, diced",
      "3 cups cooked rice (day-old is best)",
      "2 eggs, beaten",
      "1 cup frozen peas and carrots",
      "3 tbsp soy sauce",
      "2 tbsp vegetable oil",
    ],
    instructions: [
      "Heat 1 tbsp oil in a wok and scramble the eggs; remove and set aside.",
      "Add remaining oil and stir-fry peas and carrots 2 minutes.",
      "Add rice and pork, breaking up any clumps, and stir-fry 3-4 minutes.",
      "Stir in soy sauce and scrambled eggs and toss to combine.",
    ],
    tags: ["Pork", "Stir-Fry", "Asian"],
    prep_time_minutes: 10,
    cook_time_minutes: 12,
    servings: 4,
    image_url: null,
  },
  {
    id: "d032",
    title: "Bacon Ranch Pasta",
    description: "A creamy, crowd-pleasing pasta with crispy bacon and ranch flavor.",
    ingredients: [
      "1 lb penne pasta",
      "8 slices bacon, chopped",
      "1 cup sour cream",
      "1 packet ranch seasoning",
      "1 cup shredded cheddar",
      "1/2 cup pasta water, reserved",
    ],
    instructions: [
      "Cook pasta according to package directions, reserving 1/2 cup pasta water.",
      "Cook bacon in a skillet until crisp; drain excess fat, leaving a bit in the pan.",
      "Stir in sour cream, ranch seasoning, and reserved pasta water.",
      "Toss with pasta and cheddar until creamy and combined.",
    ],
    tags: ["Pork", "Pasta", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    image_url: null,
  },
  {
    id: "d033",
    title: "Sausage and White Bean Skillet",
    description: "A rustic, filling skillet with smoky sausage and creamy beans.",
    ingredients: [
      "1 lb smoked sausage, sliced",
      "2 cans white beans, drained",
      "1 cup chicken broth",
      "2 cups baby spinach",
      "2 cloves garlic, minced",
      "1 tbsp olive oil",
    ],
    instructions: [
      "Heat oil in a skillet and brown sausage slices, about 5 minutes.",
      "Add garlic and cook 30 seconds, then stir in beans and broth.",
      "Simmer 8-10 minutes until slightly thickened.",
      "Stir in spinach and cook until wilted before serving.",
    ],
    tags: ["Pork", "One-Pot", "Mediterranean"],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    image_url: null,
  },
  {
    id: "d034",
    title: "Glazed Ham Steaks",
    description: "Thick ham steaks pan-seared with a brown sugar glaze.",
    ingredients: [
      "4 ham steaks",
      "1/3 cup brown sugar",
      "2 tbsp Dijon mustard",
      "2 tbsp butter",
      "1 tbsp apple cider vinegar",
    ],
    instructions: [
      "Melt butter in a skillet over medium heat and sear ham steaks 3 minutes per side; set aside.",
      "Whisk brown sugar, mustard, and vinegar together and add to the pan.",
      "Simmer 2 minutes until syrupy.",
      "Return ham to the pan and spoon glaze over the top before serving.",
    ],
    tags: ["Pork", "American"],
    prep_time_minutes: 5,
    cook_time_minutes: 12,
    servings: 4,
    image_url: null,
  },
  {
    id: "d035",
    title: "Pork Tenderloin with Apples",
    description: "A skillet dinner pairing lean pork with sweet caramelized apples.",
    ingredients: [
      "1.5 lb pork tenderloin, sliced into medallions",
      "2 apples, sliced",
      "2 tbsp butter",
      "2 tbsp brown sugar",
      "1/2 tsp cinnamon",
      "1 tbsp olive oil",
    ],
    instructions: [
      "Season pork medallions and sear in olive oil, 3 minutes per side; set aside.",
      "Melt butter in the same pan and cook apples with brown sugar and cinnamon until softened, about 5 minutes.",
      "Return pork to the pan and simmer 2-3 minutes until cooked through.",
      "Serve pork topped with the apples.",
    ],
    tags: ["Pork", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },

  // ---------------------------------------------------------------------
  // Seafood
  // ---------------------------------------------------------------------
  {
    id: "d036",
    title: "Garlic Butter Shrimp",
    description: "Juicy shrimp in a fast garlic butter sauce, ready in 15 minutes.",
    ingredients: [
      "1.5 lbs shrimp, peeled and deveined",
      "4 tbsp butter",
      "4 cloves garlic, minced",
      "1 lemon, juiced",
      "1/4 tsp red pepper flakes",
      "2 tbsp chopped parsley",
    ],
    instructions: [
      "Melt butter in a skillet over medium heat and add garlic; cook 30 seconds.",
      "Add shrimp and red pepper flakes and cook 2-3 minutes per side until pink.",
      "Squeeze lemon juice over the shrimp and toss.",
      "Garnish with parsley and serve over rice or pasta.",
    ],
    tags: ["Seafood", "Mediterranean"],
    prep_time_minutes: 10,
    cook_time_minutes: 10,
    servings: 4,
    image_url: null,
  },
  {
    id: "d037",
    title: "Baked Lemon Salmon",
    description: "Simple, flaky baked salmon with a bright lemon-herb topping.",
    ingredients: [
      "4 salmon fillets",
      "1 lemon, sliced",
      "3 tbsp olive oil",
      "2 cloves garlic, minced",
      "1 tsp dried dill",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 400°F.",
      "Place salmon on a baking sheet and drizzle with olive oil, garlic, and dill.",
      "Top each fillet with lemon slices and season with salt and pepper.",
      "Bake 12-15 minutes until salmon flakes easily with a fork.",
    ],
    tags: ["Seafood", "Sheet-Pan", "Mediterranean"],
    prep_time_minutes: 5,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d038",
    title: "Shrimp Tacos",
    description: "Quick-cooked spiced shrimp tucked into tortillas with a crunchy slaw.",
    ingredients: [
      "1.5 lbs shrimp, peeled and deveined",
      "1 tbsp chili powder",
      "1 tsp cumin",
      "2 cups coleslaw mix",
      "1/4 cup mayonnaise",
      "1 lime, juiced",
      "8 small tortillas",
    ],
    instructions: [
      "Toss shrimp with chili powder and cumin.",
      "Mix coleslaw mix with mayonnaise and half the lime juice for a quick slaw.",
      "Cook shrimp in a hot skillet 2-3 minutes per side until pink.",
      "Fill tortillas with shrimp and slaw, and finish with remaining lime juice.",
    ],
    tags: ["Seafood", "Tacos", "Mexican"],
    prep_time_minutes: 15,
    cook_time_minutes: 8,
    servings: 4,
    image_url: null,
  },
  {
    id: "d039",
    title: "Sheet-Pan Salmon and Asparagus",
    description: "A complete, healthy dinner roasted together on one pan.",
    ingredients: [
      "4 salmon fillets",
      "1 bunch asparagus, trimmed",
      "3 tbsp olive oil",
      "2 cloves garlic, minced",
      "1 lemon",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 400°F.",
      "Arrange salmon and asparagus on a sheet pan and drizzle with olive oil and garlic.",
      "Season with salt and pepper and squeeze half the lemon over everything.",
      "Roast 12-15 minutes until salmon flakes easily and asparagus is tender.",
    ],
    tags: ["Seafood", "Sheet-Pan", "Mediterranean"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d040",
    title: "Shrimp Scampi",
    description: "Garlicky, buttery shrimp tossed with pasta in a classic scampi sauce.",
    ingredients: [
      "1.5 lbs shrimp, peeled and deveined",
      "12 oz linguine",
      "4 tbsp butter",
      "4 cloves garlic, minced",
      "1/2 cup white wine or chicken broth",
      "1 lemon, juiced",
    ],
    instructions: [
      "Cook linguine according to package directions.",
      "Melt butter in a skillet, add garlic, and cook 30 seconds.",
      "Add shrimp and cook 2-3 minutes per side until pink; remove.",
      "Pour in wine and lemon juice, simmer 2 minutes, then toss with shrimp and pasta.",
    ],
    tags: ["Seafood", "Pasta", "Italian"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d041",
    title: "Fish Tacos with Slaw",
    description: "Flaky white fish tacos with a tangy, crunchy cabbage slaw.",
    ingredients: [
      "1.5 lbs white fish fillets (cod or tilapia)",
      "1 tbsp taco seasoning",
      "2 cups shredded cabbage",
      "1/4 cup sour cream",
      "1 lime, juiced",
      "8 small tortillas",
    ],
    instructions: [
      "Season fish with taco seasoning.",
      "Cook fish in a skillet over medium heat 3-4 minutes per side until it flakes easily.",
      "Mix cabbage, sour cream, and lime juice for the slaw.",
      "Flake the fish into tortillas and top with slaw.",
    ],
    tags: ["Seafood", "Tacos", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 10,
    servings: 4,
    image_url: null,
  },
  {
    id: "d042",
    title: "Blackened Tilapia",
    description: "Spice-crusted tilapia fillets with a smoky kick, pan-seared fast.",
    ingredients: [
      "4 tilapia fillets",
      "2 tbsp blackening or Cajun seasoning",
      "2 tbsp butter",
      "1 tbsp olive oil",
      "1 lemon, cut into wedges",
    ],
    instructions: [
      "Pat fillets dry and coat both sides with blackening seasoning.",
      "Heat butter and oil in a skillet over medium-high heat.",
      "Cook fillets 3 minutes per side until blackened and opaque throughout.",
      "Serve with lemon wedges.",
    ],
    tags: ["Seafood", "American"],
    prep_time_minutes: 5,
    cook_time_minutes: 8,
    servings: 4,
    image_url: null,
  },
  {
    id: "d043",
    title: "Shrimp Fried Rice",
    description: "A fast, restaurant-style fried rice loaded with shrimp.",
    ingredients: [
      "1 lb shrimp, peeled and deveined",
      "3 cups cooked rice (day-old is best)",
      "2 eggs, beaten",
      "1 cup frozen peas and carrots",
      "3 tbsp soy sauce",
      "2 tbsp vegetable oil",
    ],
    instructions: [
      "Heat 1 tbsp oil in a wok and cook shrimp until pink, about 3 minutes; remove.",
      "Scramble eggs in the same wok and remove.",
      "Add remaining oil, peas and carrots, and rice; stir-fry 3-4 minutes.",
      "Return shrimp and eggs to the wok, add soy sauce, and toss to combine.",
    ],
    tags: ["Seafood", "Stir-Fry", "Asian"],
    prep_time_minutes: 10,
    cook_time_minutes: 12,
    servings: 4,
    image_url: null,
  },
  {
    id: "d044",
    title: "Tuna Melt Skillet",
    description: "An open-faced tuna melt sandwich, toasted until golden and cheesy.",
    ingredients: [
      "2 cans tuna, drained",
      "1/3 cup mayonnaise",
      "1 celery stalk, diced",
      "4 slices bread",
      "4 slices cheddar cheese",
      "2 tbsp butter, softened",
    ],
    instructions: [
      "Mix tuna, mayonnaise, and celery together.",
      "Butter one side of each bread slice and place butter-side down in a skillet.",
      "Top with tuna mixture and a slice of cheese.",
      "Cook over medium-low heat until bread is golden and cheese is melted, about 4 minutes.",
    ],
    tags: ["Seafood", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 8,
    servings: 4,
    image_url: null,
  },
  {
    id: "d045",
    title: "Cajun Shrimp Pasta",
    description: "Creamy, spicy Cajun-seasoned shrimp tossed with pasta.",
    ingredients: [
      "1.5 lbs shrimp, peeled and deveined",
      "12 oz penne pasta",
      "2 tbsp Cajun seasoning",
      "1 cup heavy cream",
      "1/2 cup grated parmesan",
      "2 tbsp butter",
    ],
    instructions: [
      "Cook pasta according to package directions.",
      "Toss shrimp with Cajun seasoning and cook in butter 2-3 minutes per side; remove.",
      "Pour cream into the pan and simmer 3 minutes, then stir in parmesan.",
      "Toss pasta and shrimp with the sauce until coated.",
    ],
    tags: ["Seafood", "Pasta", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    image_url: null,
  },

  // ---------------------------------------------------------------------
  // Pasta / Italian
  // ---------------------------------------------------------------------
  {
    id: "d046",
    title: "Spaghetti Aglio e Olio",
    description: "A pantry-staple Italian classic: garlic, olive oil, and pasta.",
    ingredients: [
      "1 lb spaghetti",
      "1/2 cup olive oil",
      "6 cloves garlic, sliced thin",
      "1/2 tsp red pepper flakes",
      "1/4 cup chopped parsley",
      "1/2 cup grated parmesan",
    ],
    instructions: [
      "Cook spaghetti according to package directions, reserving 1/2 cup pasta water.",
      "Heat olive oil in a large skillet and gently cook garlic until golden, being careful not to burn it.",
      "Add red pepper flakes, then toss in the drained pasta and a splash of pasta water.",
      "Stir in parsley and parmesan before serving.",
    ],
    tags: ["Pasta", "Vegetarian", "Italian"],
    prep_time_minutes: 5,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d047",
    title: "Creamy Tomato Pasta",
    description: "A rich, cozy tomato sauce made creamy with a splash of cream.",
    ingredients: [
      "1 lb penne pasta",
      "1 can crushed tomatoes",
      "1/2 cup heavy cream",
      "3 cloves garlic, minced",
      "2 tbsp olive oil",
      "1/2 cup grated parmesan",
    ],
    instructions: [
      "Cook pasta according to package directions.",
      "Heat olive oil in a saucepan and cook garlic 30 seconds.",
      "Add crushed tomatoes and simmer 10 minutes, then stir in cream and parmesan.",
      "Toss with pasta and serve.",
    ],
    tags: ["Pasta", "Vegetarian", "Italian"],
    prep_time_minutes: 5,
    cook_time_minutes: 20,
    servings: 4,
    image_url: null,
  },
  {
    id: "d048",
    title: "One-Pot Chicken Alfredo",
    description: "Creamy alfredo pasta and chicken cooked together in a single pot.",
    ingredients: [
      "1.5 lbs chicken breast, cubed",
      "12 oz fettuccine",
      "4 cups chicken broth",
      "1 cup heavy cream",
      "1 cup grated parmesan",
      "2 cloves garlic, minced",
    ],
    instructions: [
      "Sear chicken in a large pot until browned; add garlic and cook 30 seconds.",
      "Pour in broth and fettuccine, bring to a boil, then simmer uncovered 12-14 minutes, stirring occasionally.",
      "Once pasta is tender and liquid has mostly absorbed, stir in cream and parmesan.",
      "Simmer 2-3 minutes until creamy and thickened.",
    ],
    tags: ["Chicken", "Pasta", "One-Pot", "Italian"],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    image_url: null,
  },
  {
    id: "d049",
    title: "Pasta Primavera",
    description: "A light pasta tossed with a colorful medley of fresh vegetables.",
    ingredients: [
      "1 lb penne pasta",
      "2 cups mixed vegetables (zucchini, bell pepper, carrots)",
      "3 tbsp olive oil",
      "2 cloves garlic, minced",
      "1/2 cup grated parmesan",
      "1 tsp Italian seasoning",
    ],
    instructions: [
      "Cook pasta according to package directions.",
      "Heat olive oil in a skillet and sauté vegetables with garlic and Italian seasoning until crisp-tender.",
      "Toss vegetables with pasta and parmesan.",
      "Add a splash of pasta water if needed to loosen the sauce.",
    ],
    tags: ["Pasta", "Vegetarian", "Italian"],
    prep_time_minutes: 15,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d050",
    title: "Baked Ziti",
    description: "Cheesy baked pasta that's easy to prep ahead for a busy night.",
    ingredients: [
      "1 lb ziti pasta",
      "1 jar marinara sauce",
      "15 oz ricotta cheese",
      "2 cups shredded mozzarella",
      "1/2 cup grated parmesan",
      "1 egg",
    ],
    instructions: [
      "Preheat oven to 375°F and cook ziti until just shy of al dente.",
      "Mix ricotta, egg, and half the parmesan together.",
      "Toss pasta with marinara, then layer half in a baking dish, dollop with ricotta mixture, and top with remaining pasta.",
      "Top with mozzarella and remaining parmesan and bake 20-25 minutes until bubbly.",
    ],
    tags: ["Pasta", "Vegetarian", "Italian"],
    prep_time_minutes: 15,
    cook_time_minutes: 30,
    servings: 6,
    image_url: null,
  },
  {
    id: "d051",
    title: "Pesto Pasta with Cherry Tomatoes",
    description: "A vibrant, fast pasta with basil pesto and burst cherry tomatoes.",
    ingredients: [
      "1 lb fusilli or penne pasta",
      "1/2 cup basil pesto",
      "2 cups cherry tomatoes, halved",
      "1/2 cup grated parmesan",
      "2 tbsp olive oil",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Cook pasta according to package directions, reserving 1/4 cup pasta water.",
      "Heat olive oil in a skillet and cook cherry tomatoes 3-4 minutes until they start to burst.",
      "Toss pasta with pesto, tomatoes, and reserved pasta water.",
      "Top with parmesan before serving.",
    ],
    tags: ["Pasta", "Vegetarian", "Italian"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d052",
    title: "Sausage and Spinach Pasta",
    description: "A quick, satisfying pasta with Italian sausage and wilted spinach.",
    ingredients: [
      "1 lb Italian sausage, casings removed",
      "1 lb rigatoni",
      "3 cups baby spinach",
      "1/2 cup heavy cream",
      "3 cloves garlic, minced",
      "1/2 cup grated parmesan",
    ],
    instructions: [
      "Cook rigatoni according to package directions.",
      "Brown sausage in a skillet, breaking it up as it cooks; add garlic and cook 30 seconds.",
      "Stir in cream and spinach and cook until spinach wilts.",
      "Toss with pasta and parmesan before serving.",
    ],
    tags: ["Pork", "Pasta", "Italian"],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    image_url: null,
  },
  {
    id: "d053",
    title: "Lemon Ricotta Pasta",
    description: "A light, creamy pasta brightened with lemon and fresh ricotta.",
    ingredients: [
      "1 lb spaghetti",
      "1 cup ricotta cheese",
      "1 lemon, zested and juiced",
      "1/2 cup grated parmesan",
      "2 tbsp olive oil",
      "1/4 cup chopped basil",
    ],
    instructions: [
      "Cook spaghetti according to package directions, reserving 1/2 cup pasta water.",
      "Whisk ricotta, lemon zest, lemon juice, and a splash of pasta water into a creamy sauce.",
      "Toss pasta with the ricotta sauce and parmesan, adding more pasta water as needed.",
      "Finish with olive oil and fresh basil.",
    ],
    tags: ["Pasta", "Vegetarian", "Italian"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d054",
    title: "Stovetop Mac and Cheese",
    description: "Creamy, from-scratch mac and cheese ready faster than the boxed kind.",
    ingredients: [
      "1 lb elbow macaroni",
      "3 tbsp butter",
      "3 tbsp flour",
      "2 cups milk",
      "3 cups shredded cheddar",
      "1/2 tsp mustard powder",
    ],
    instructions: [
      "Cook macaroni according to package directions.",
      "Melt butter in a saucepan, whisk in flour, and cook 1 minute.",
      "Slowly whisk in milk and cook until thickened, about 5 minutes.",
      "Remove from heat, stir in cheddar and mustard powder until melted, then toss with pasta.",
    ],
    tags: ["Pasta", "Vegetarian", "American"],
    prep_time_minutes: 5,
    cook_time_minutes: 20,
    servings: 4,
    image_url: null,
  },
  {
    id: "d055",
    title: "Tortellini with Brown Butter",
    description: "Store-bought tortellini elevated with a nutty brown butter sage sauce.",
    ingredients: [
      "20 oz cheese tortellini",
      "6 tbsp butter",
      "8 fresh sage leaves",
      "1/2 cup grated parmesan",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Cook tortellini according to package directions.",
      "Melt butter in a skillet over medium heat until it turns golden brown and smells nutty, about 4 minutes.",
      "Add sage leaves and cook 30 seconds until crisp.",
      "Toss tortellini with the brown butter and top with parmesan.",
    ],
    tags: ["Pasta", "Vegetarian", "Italian"],
    prep_time_minutes: 5,
    cook_time_minutes: 12,
    servings: 4,
    image_url: null,
  },
  {
    id: "d056",
    title: "Cacio e Pepe",
    description: "A four-ingredient Roman pasta of cheese and black pepper.",
    ingredients: [
      "1 lb spaghetti",
      "1.5 cups grated pecorino romano",
      "2 tsp coarsely ground black pepper",
      "2 tbsp butter",
    ],
    instructions: [
      "Cook spaghetti according to package directions, reserving 1 cup pasta water.",
      "Toast black pepper in a dry skillet 30 seconds, then add butter and a splash of pasta water.",
      "Add pasta to the skillet and toss, gradually adding pecorino and pasta water off heat until creamy.",
      "Serve immediately.",
    ],
    tags: ["Pasta", "Vegetarian", "Italian"],
    prep_time_minutes: 5,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d057",
    title: "Caprese Pasta Salad",
    description: "A cool, no-cook-sauce pasta salad with tomato, mozzarella, and basil.",
    ingredients: [
      "1 lb rotini pasta",
      "2 cups cherry tomatoes, halved",
      "8 oz mozzarella pearls",
      "1/4 cup olive oil",
      "2 tbsp balsamic vinegar",
      "1/4 cup chopped basil",
    ],
    instructions: [
      "Cook pasta according to package directions and let cool slightly.",
      "Toss pasta with tomatoes, mozzarella, olive oil, and balsamic vinegar.",
      "Stir in basil and season with salt and pepper.",
      "Serve warm or chilled.",
    ],
    tags: ["Pasta", "Vegetarian", "Italian"],
    prep_time_minutes: 15,
    cook_time_minutes: 10,
    servings: 4,
    image_url: null,
  },

  // ---------------------------------------------------------------------
  // Vegetarian
  // ---------------------------------------------------------------------
  {
    id: "d058",
    title: "Black Bean Tacos",
    description: "Seasoned black beans make a hearty, meatless taco filling.",
    ingredients: [
      "2 cans black beans, drained",
      "1 tbsp chili powder",
      "1 tsp cumin",
      "8 small tortillas",
      "1 cup shredded cheese",
      "1 avocado, sliced",
    ],
    instructions: [
      "Heat black beans in a saucepan with chili powder and cumin, mashing some for texture.",
      "Warm tortillas.",
      "Fill tortillas with beans, cheese, and avocado.",
      "Top with your favorite salsa or hot sauce.",
    ],
    tags: ["Vegetarian", "Tacos", "Mexican"],
    prep_time_minutes: 5,
    cook_time_minutes: 10,
    servings: 4,
    image_url: null,
  },
  {
    id: "d059",
    title: "Veggie Stir-Fry with Tofu",
    description: "Crispy tofu and crunchy vegetables in a savory garlic-ginger sauce.",
    ingredients: [
      "14 oz firm tofu, cubed",
      "4 cups mixed stir-fry vegetables",
      "3 tbsp soy sauce",
      "1 tbsp cornstarch",
      "1 tsp fresh ginger, grated",
      "2 tbsp vegetable oil",
    ],
    instructions: [
      "Toss tofu with 1 tbsp cornstarch and pan-fry in 1 tbsp oil until golden on all sides; set aside.",
      "Heat remaining oil and stir-fry vegetables with ginger 3-4 minutes.",
      "Whisk soy sauce, remaining cornstarch, and 1/4 cup water together and pour into the pan.",
      "Return tofu to the pan and toss until sauce thickens.",
    ],
    tags: ["Vegetarian", "Stir-Fry", "Asian"],
    prep_time_minutes: 15,
    cook_time_minutes: 12,
    servings: 4,
    image_url: null,
  },
  {
    id: "d060",
    title: "Caprese Grilled Cheese",
    description: "A gooey grilled cheese upgraded with tomato, basil, and mozzarella.",
    ingredients: [
      "8 slices sourdough bread",
      "8 oz fresh mozzarella, sliced",
      "1 tomato, sliced",
      "8 fresh basil leaves",
      "4 tbsp butter, softened",
      "2 tbsp balsamic glaze (optional)",
    ],
    instructions: [
      "Butter one side of each bread slice.",
      "Layer mozzarella, tomato, and basil on the unbuttered side of half the slices; top with remaining bread, butter-side out.",
      "Cook in a skillet over medium heat 3-4 minutes per side until golden and cheese melts.",
      "Drizzle with balsamic glaze if using and serve.",
    ],
    tags: ["Vegetarian", "Italian"],
    prep_time_minutes: 10,
    cook_time_minutes: 10,
    servings: 4,
    image_url: null,
  },
  {
    id: "d061",
    title: "Sheet-Pan Roasted Vegetables with Chickpeas",
    description: "A simple, filling vegetarian dinner roasted on one pan.",
    ingredients: [
      "2 cans chickpeas, drained",
      "4 cups mixed vegetables (broccoli, carrots, bell pepper)",
      "3 tbsp olive oil",
      "1 tsp smoked paprika",
      "1 tsp garlic powder",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 425°F.",
      "Toss chickpeas and vegetables with olive oil, paprika, garlic powder, salt, and pepper on a sheet pan.",
      "Spread in a single layer and roast 25-30 minutes, stirring halfway, until vegetables are tender and chickpeas are crisp.",
      "Serve as-is or over rice.",
    ],
    tags: ["Vegetarian", "Sheet-Pan", "Mediterranean"],
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings: 4,
    image_url: null,
  },
  {
    id: "d062",
    title: "Vegetable Fried Rice",
    description: "A fast, flexible fried rice that's perfect for using up leftover veggies.",
    ingredients: [
      "3 cups cooked rice (day-old is best)",
      "2 eggs, beaten",
      "2 cups mixed frozen vegetables",
      "3 tbsp soy sauce",
      "2 tbsp vegetable oil",
      "2 green onions, sliced",
    ],
    instructions: [
      "Heat 1 tbsp oil in a wok and scramble eggs; remove and set aside.",
      "Add remaining oil and stir-fry vegetables 3-4 minutes.",
      "Add rice, breaking up clumps, and stir-fry 3-4 minutes.",
      "Stir in soy sauce, eggs, and green onions and toss to combine.",
    ],
    tags: ["Vegetarian", "Stir-Fry", "Asian"],
    prep_time_minutes: 10,
    cook_time_minutes: 12,
    servings: 4,
    image_url: null,
  },
  {
    id: "d063",
    title: "Black Bean Quesadillas",
    description: "Crispy, cheesy quesadillas packed with seasoned black beans.",
    ingredients: [
      "1 can black beans, drained and mashed",
      "2 cups shredded cheese",
      "8 small tortillas",
      "1 tsp cumin",
      "1 tsp chili powder",
      "Butter, for the pan",
    ],
    instructions: [
      "Mix mashed black beans with cumin and chili powder.",
      "Spread beans and cheese between two tortillas.",
      "Cook in a buttered skillet over medium heat 3 minutes per side until golden and cheese is melted.",
      "Slice into wedges and serve.",
    ],
    tags: ["Vegetarian", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d064",
    title: "Lentil Soup",
    description: "A hearty, protein-packed soup that comes together in one pot.",
    ingredients: [
      "1.5 cups dried lentils, rinsed",
      "1 onion, diced",
      "2 carrots, diced",
      "2 celery stalks, diced",
      "6 cups vegetable broth",
      "1 tsp cumin",
    ],
    instructions: [
      "Sauté onion, carrots, and celery in a large pot until softened, about 5 minutes.",
      "Add lentils, broth, and cumin.",
      "Bring to a boil, then reduce heat and simmer 25-30 minutes until lentils are tender.",
      "Season with salt and pepper before serving.",
    ],
    tags: ["Vegetarian", "Soup", "One-Pot", "Mediterranean"],
    prep_time_minutes: 10,
    cook_time_minutes: 35,
    servings: 6,
    image_url: null,
  },
  {
    id: "d065",
    title: "Veggie Burrito Bowls",
    description: "A build-your-own bowl with rice, beans, and roasted veggies.",
    ingredients: [
      "2 cups cooked rice",
      "1 can black beans, drained",
      "2 cups roasted or sautéed peppers and onions",
      "1 avocado, sliced",
      "1 cup corn",
      "1 lime, juiced",
    ],
    instructions: [
      "Warm rice, beans, and vegetables separately or together.",
      "Divide rice among bowls and top with beans, vegetables, corn, and avocado.",
      "Squeeze lime juice over the top before serving.",
    ],
    tags: ["Vegetarian", "Mexican"],
    prep_time_minutes: 15,
    cook_time_minutes: 10,
    servings: 4,
    image_url: null,
  },
  {
    id: "d066",
    title: "Stuffed Sweet Potatoes",
    description: "Baked sweet potatoes loaded with a savory black bean filling.",
    ingredients: [
      "4 sweet potatoes",
      "1 can black beans, drained",
      "1 tsp cumin",
      "1 cup shredded cheese",
      "1/2 cup sour cream",
      "2 green onions, sliced",
    ],
    instructions: [
      "Pierce sweet potatoes and microwave 8-10 minutes (or bake at 400°F for 45 minutes) until tender.",
      "Warm black beans with cumin.",
      "Split potatoes open and top with beans, cheese, sour cream, and green onions.",
    ],
    tags: ["Vegetarian", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d067",
    title: "Margherita Flatbread",
    description: "A quick flatbread pizza with tomato, mozzarella, and fresh basil.",
    ingredients: [
      "4 naan or flatbreads",
      "1/2 cup marinara sauce",
      "8 oz fresh mozzarella, sliced",
      "1 tomato, sliced thin",
      "8 fresh basil leaves",
      "2 tbsp olive oil",
    ],
    instructions: [
      "Preheat oven to 425°F.",
      "Spread marinara over flatbreads and top with mozzarella and tomato slices.",
      "Bake 8-10 minutes until cheese is melted and bubbly.",
      "Top with fresh basil and a drizzle of olive oil before serving.",
    ],
    tags: ["Vegetarian", "Italian"],
    prep_time_minutes: 10,
    cook_time_minutes: 10,
    servings: 4,
    image_url: null,
  },
  {
    id: "d068",
    title: "Chickpea Curry",
    description: "A warmly spiced, creamy chickpea curry ready in one pot.",
    ingredients: [
      "2 cans chickpeas, drained",
      "1 can coconut milk",
      "1 can diced tomatoes",
      "1 onion, diced",
      "2 tbsp curry powder",
      "2 cloves garlic, minced",
    ],
    instructions: [
      "Sauté onion and garlic in a large pot until softened.",
      "Stir in curry powder and cook 1 minute until fragrant.",
      "Add chickpeas, tomatoes, and coconut milk.",
      "Simmer 15-20 minutes until slightly thickened, then serve over rice.",
    ],
    tags: ["Vegetarian", "One-Pot", "Indian"],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings: 4,
    image_url: null,
  },
  {
    id: "d069",
    title: "Veggie Fajita Bowls",
    description: "Sizzling peppers and onions over rice for a meatless fajita night.",
    ingredients: [
      "2 bell peppers, sliced",
      "1 onion, sliced",
      "1 can black beans, drained",
      "2 cups cooked rice",
      "2 tbsp fajita seasoning",
      "2 tbsp olive oil",
    ],
    instructions: [
      "Heat oil in a skillet and cook peppers and onion with fajita seasoning until tender, about 8 minutes.",
      "Warm black beans separately.",
      "Divide rice among bowls and top with peppers, onions, and black beans.",
      "Serve with your favorite toppings.",
    ],
    tags: ["Vegetarian", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 12,
    servings: 4,
    image_url: null,
  },

  // ---------------------------------------------------------------------
  // Soups & Stews
  // ---------------------------------------------------------------------
  {
    id: "d070",
    title: "Weeknight Chicken Noodle Soup",
    description: "A comforting classic that comes together with pantry staples.",
    ingredients: [
      "2 cups shredded cooked chicken",
      "8 cups chicken broth",
      "2 carrots, sliced",
      "2 celery stalks, sliced",
      "2 cups egg noodles",
      "1 tsp dried thyme",
    ],
    instructions: [
      "Bring broth to a boil in a large pot with carrots and celery.",
      "Simmer 8 minutes until vegetables begin to soften.",
      "Add noodles and cook according to package time.",
      "Stir in chicken and thyme and heat through before serving.",
    ],
    tags: ["Chicken", "Soup", "One-Pot", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 6,
    image_url: null,
  },
  {
    id: "d071",
    title: "Taco Soup",
    description: "All your favorite taco flavors in a hearty, easy soup.",
    ingredients: [
      "1 lb ground beef",
      "1 packet taco seasoning",
      "1 can black beans, drained",
      "1 can corn, drained",
      "1 can diced tomatoes",
      "3 cups beef broth",
    ],
    instructions: [
      "Brown ground beef in a large pot; drain excess fat.",
      "Stir in taco seasoning, beans, corn, tomatoes, and broth.",
      "Bring to a simmer and cook 15-20 minutes.",
      "Top with cheese, sour cream, or tortilla chips before serving.",
    ],
    tags: ["Beef", "Soup", "One-Pot", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings: 6,
    image_url: null,
  },
  {
    id: "d072",
    title: "Tomato Basil Soup",
    description: "A smooth, comforting tomato soup that's perfect with grilled cheese.",
    ingredients: [
      "2 cans crushed tomatoes",
      "3 cups vegetable broth",
      "1 onion, diced",
      "2 cloves garlic, minced",
      "1/2 cup heavy cream",
      "1/4 cup fresh basil, chopped",
    ],
    instructions: [
      "Sauté onion and garlic in a pot until softened.",
      "Add crushed tomatoes and broth and simmer 15 minutes.",
      "Blend until smooth (or leave chunky), then stir in cream.",
      "Stir in fresh basil before serving.",
    ],
    tags: ["Vegetarian", "Soup", "One-Pot", "Italian"],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    image_url: null,
  },
  {
    id: "d073",
    title: "Turkey Chili",
    description: "A lighter take on chili using ground turkey and plenty of beans.",
    ingredients: [
      "1.5 lbs ground turkey",
      "1 onion, diced",
      "2 cans kidney or pinto beans, drained",
      "1 can diced tomatoes",
      "2 tbsp chili powder",
      "2 cups chicken broth",
    ],
    instructions: [
      "Brown ground turkey with onion in a large pot.",
      "Stir in chili powder and cook 1 minute.",
      "Add beans, tomatoes, and broth; bring to a simmer.",
      "Cook uncovered 25 minutes, stirring occasionally, until thickened.",
    ],
    tags: ["Soup", "One-Pot", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings: 6,
    image_url: null,
  },
  {
    id: "d074",
    title: "Minestrone Soup",
    description: "A vegetable-packed Italian soup with beans and small pasta.",
    ingredients: [
      "1 onion, diced",
      "2 carrots, diced",
      "2 celery stalks, diced",
      "1 can diced tomatoes",
      "1 can kidney beans, drained",
      "1 cup small pasta (ditalini or elbow)",
      "6 cups vegetable broth",
    ],
    instructions: [
      "Sauté onion, carrots, and celery in a large pot until softened.",
      "Add tomatoes, beans, and broth and bring to a boil.",
      "Stir in pasta and simmer 10-12 minutes until tender.",
      "Season with salt, pepper, and Italian herbs to taste.",
    ],
    tags: ["Vegetarian", "Soup", "One-Pot", "Italian"],
    prep_time_minutes: 15,
    cook_time_minutes: 25,
    servings: 6,
    image_url: null,
  },
  {
    id: "d075",
    title: "Broccoli Cheddar Soup",
    description: "A creamy, cheesy soup loaded with tender broccoli.",
    ingredients: [
      "4 cups broccoli florets",
      "4 cups chicken or vegetable broth",
      "1 onion, diced",
      "2 tbsp flour",
      "2 cups shredded cheddar",
      "1 cup half-and-half",
    ],
    instructions: [
      "Sauté onion in a large pot until softened, then whisk in flour and cook 1 minute.",
      "Pour in broth, add broccoli, and simmer 12-15 minutes until tender.",
      "Blend partially for a thicker texture if desired.",
      "Stir in half-and-half and cheddar until melted and smooth.",
    ],
    tags: ["Vegetarian", "Soup", "One-Pot", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings: 4,
    image_url: null,
  },
  {
    id: "d076",
    title: "White Chicken Chili",
    description: "A creamy, mild chili made with white beans and shredded chicken.",
    ingredients: [
      "2 cups shredded cooked chicken",
      "2 cans white beans, drained",
      "1 can diced green chiles",
      "4 cups chicken broth",
      "1 tsp cumin",
      "1/2 cup sour cream",
    ],
    instructions: [
      "Combine chicken, beans, green chiles, broth, and cumin in a large pot.",
      "Bring to a simmer and cook 15 minutes.",
      "Remove from heat and stir in sour cream.",
      "Top with shredded cheese or tortilla strips before serving.",
    ],
    tags: ["Chicken", "Soup", "One-Pot", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 6,
    image_url: null,
  },
  {
    id: "d077",
    title: "Potato Leek Soup",
    description: "A silky, comforting soup that's simple enough for any weeknight.",
    ingredients: [
      "4 potatoes, peeled and diced",
      "2 leeks, sliced (white and light green parts)",
      "4 cups vegetable broth",
      "1/2 cup heavy cream",
      "2 tbsp butter",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Melt butter in a pot and sauté leeks until softened, about 5 minutes.",
      "Add potatoes and broth and simmer 20 minutes until potatoes are tender.",
      "Blend until smooth (or mash for a chunkier texture).",
      "Stir in cream and season with salt and pepper before serving.",
    ],
    tags: ["Vegetarian", "Soup", "One-Pot", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings: 4,
    image_url: null,
  },

  // ---------------------------------------------------------------------
  // Asian-inspired
  // ---------------------------------------------------------------------
  {
    id: "d078",
    title: "Chicken Lo Mein",
    description: "Soft noodles tossed with chicken and vegetables in a savory sauce.",
    ingredients: [
      "1.5 lbs chicken breast, sliced thin",
      "12 oz lo mein or spaghetti noodles",
      "3 cups mixed stir-fry vegetables",
      "1/3 cup soy sauce",
      "1 tbsp sesame oil",
      "2 cloves garlic, minced",
    ],
    instructions: [
      "Cook noodles according to package directions.",
      "Stir-fry chicken in a wok until cooked through, about 6 minutes; set aside.",
      "Add vegetables and garlic and stir-fry 3-4 minutes.",
      "Return chicken to the wok, add noodles, soy sauce, and sesame oil, and toss to combine.",
    ],
    tags: ["Chicken", "Stir-Fry", "Asian"],
    prep_time_minutes: 15,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d079",
    title: "Sesame Noodles",
    description: "Cold or warm noodles tossed in a nutty sesame-soy sauce.",
    ingredients: [
      "1 lb spaghetti or lo mein noodles",
      "1/4 cup soy sauce",
      "2 tbsp sesame oil",
      "2 tbsp peanut butter",
      "1 tbsp rice vinegar",
      "2 green onions, sliced",
    ],
    instructions: [
      "Cook noodles according to package directions and drain.",
      "Whisk soy sauce, sesame oil, peanut butter, and vinegar together.",
      "Toss noodles with the sauce until evenly coated.",
      "Top with green onions and sesame seeds before serving.",
    ],
    tags: ["Vegetarian", "Asian"],
    prep_time_minutes: 5,
    cook_time_minutes: 10,
    servings: 4,
    image_url: null,
  },
  {
    id: "d080",
    title: "Teriyaki Salmon",
    description: "Glazed salmon fillets with a homemade sweet-savory teriyaki sauce.",
    ingredients: [
      "4 salmon fillets",
      "1/3 cup soy sauce",
      "3 tbsp brown sugar",
      "1 tbsp rice vinegar",
      "1 clove garlic, minced",
      "1 tsp cornstarch",
    ],
    instructions: [
      "Whisk soy sauce, brown sugar, vinegar, garlic, and cornstarch together.",
      "Sear salmon in a skillet 3-4 minutes per side until nearly cooked through.",
      "Pour sauce into the pan and simmer 2 minutes until glossy and thickened.",
      "Spoon sauce over salmon and serve with rice.",
    ],
    tags: ["Seafood", "Asian"],
    prep_time_minutes: 5,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d081",
    title: "Kung Pao Chicken",
    description: "A spicy, peanutty stir-fry classic made easy at home.",
    ingredients: [
      "1.5 lbs chicken breast, cubed",
      "1/2 cup roasted peanuts",
      "3 tbsp soy sauce",
      "1 tbsp rice vinegar",
      "1 tbsp chili garlic sauce",
      "1 bell pepper, diced",
    ],
    instructions: [
      "Stir-fry chicken in a wok until browned and cooked through, about 6 minutes; set aside.",
      "Add bell pepper and stir-fry 2-3 minutes.",
      "Whisk soy sauce, vinegar, and chili garlic sauce together and pour into the wok.",
      "Return chicken to the wok, add peanuts, and toss until coated.",
    ],
    tags: ["Chicken", "Stir-Fry", "Asian"],
    prep_time_minutes: 15,
    cook_time_minutes: 12,
    servings: 4,
    image_url: null,
  },
  {
    id: "d082",
    title: "Beef and Snap Pea Stir-Fry",
    description: "Tender beef and crisp snap peas in a quick garlic-soy sauce.",
    ingredients: [
      "1 lb flank steak, sliced thin",
      "3 cups sugar snap peas",
      "3 tbsp soy sauce",
      "1 tbsp oyster sauce",
      "1 tbsp cornstarch",
      "2 cloves garlic, minced",
    ],
    instructions: [
      "Whisk soy sauce, oyster sauce, cornstarch, and 1/4 cup water together.",
      "Stir-fry beef in a hot wok until browned, about 3 minutes; set aside.",
      "Add snap peas and garlic and stir-fry 2-3 minutes.",
      "Return beef to the wok, pour in sauce, and cook until thickened.",
    ],
    tags: ["Beef", "Stir-Fry", "Asian"],
    prep_time_minutes: 15,
    cook_time_minutes: 10,
    servings: 4,
    image_url: null,
  },
  {
    id: "d083",
    title: "Vegetable Spring Roll Bowls",
    description: "All the flavors of spring rolls served easy as a deconstructed bowl.",
    ingredients: [
      "8 oz rice noodles",
      "2 cups shredded carrots and cabbage slaw mix",
      "1 cucumber, julienned",
      "1/4 cup peanut sauce",
      "1/4 cup chopped peanuts",
      "1/4 cup fresh mint or basil",
    ],
    instructions: [
      "Cook rice noodles according to package directions and drain.",
      "Divide noodles among bowls and top with slaw mix and cucumber.",
      "Drizzle with peanut sauce.",
      "Top with chopped peanuts and fresh herbs before serving.",
    ],
    tags: ["Vegetarian", "Asian"],
    prep_time_minutes: 15,
    cook_time_minutes: 10,
    servings: 4,
    image_url: null,
  },
  {
    id: "d084",
    title: "Orange Chicken",
    description: "Crispy chicken pieces glazed in a tangy-sweet orange sauce.",
    ingredients: [
      "1.5 lbs chicken thighs, cubed",
      "1/3 cup cornstarch",
      "2 tbsp vegetable oil",
      "1/2 cup orange juice",
      "3 tbsp soy sauce",
      "3 tbsp brown sugar",
    ],
    instructions: [
      "Toss chicken with cornstarch and pan-fry in oil until golden and cooked through, about 8 minutes.",
      "Whisk orange juice, soy sauce, and brown sugar together.",
      "Pour sauce over chicken in the pan and simmer 3-4 minutes until thickened.",
      "Serve over rice.",
    ],
    tags: ["Chicken", "Asian"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d085",
    title: "Thai Peanut Noodles",
    description: "Rich peanut sauce tossed with noodles and crunchy vegetables.",
    ingredients: [
      "12 oz noodles (rice or spaghetti)",
      "1/3 cup peanut butter",
      "3 tbsp soy sauce",
      "2 tbsp lime juice",
      "1 tbsp honey",
      "2 cups shredded carrots and cabbage",
    ],
    instructions: [
      "Cook noodles according to package directions and drain.",
      "Whisk peanut butter, soy sauce, lime juice, honey, and a splash of warm water into a sauce.",
      "Toss noodles with the sauce and shredded vegetables.",
      "Top with chopped peanuts and cilantro if desired.",
    ],
    tags: ["Vegetarian", "Asian"],
    prep_time_minutes: 10,
    cook_time_minutes: 10,
    servings: 4,
    image_url: null,
  },

  // ---------------------------------------------------------------------
  // Mexican
  // ---------------------------------------------------------------------
  {
    id: "d086",
    title: "Chicken Enchiladas",
    description: "Rolled tortillas stuffed with chicken and smothered in enchilada sauce.",
    ingredients: [
      "2 cups shredded cooked chicken",
      "10 small tortillas",
      "2 cups enchilada sauce",
      "2 cups shredded cheddar",
      "1/2 cup sour cream",
      "1 tsp cumin",
    ],
    instructions: [
      "Preheat oven to 375°F.",
      "Toss chicken with cumin and a splash of enchilada sauce.",
      "Fill tortillas with chicken and roll, placing seam-side down in a baking dish.",
      "Pour remaining sauce over the top, sprinkle with cheese, and bake 20 minutes until bubbly.",
    ],
    tags: ["Chicken", "Mexican"],
    prep_time_minutes: 15,
    cook_time_minutes: 25,
    servings: 5,
    image_url: null,
  },
  {
    id: "d087",
    title: "Ground Beef Nachos",
    description: "A big sheet pan of loaded nachos, perfect for a casual dinner.",
    ingredients: [
      "1 lb ground beef",
      "1 packet taco seasoning",
      "1 bag tortilla chips",
      "2 cups shredded cheddar",
      "1 can black beans, drained",
      "1 tomato, diced",
    ],
    instructions: [
      "Preheat oven to 400°F.",
      "Brown ground beef and stir in taco seasoning with 1/2 cup water.",
      "Spread tortilla chips on a sheet pan and top with beef, beans, and cheese.",
      "Bake 8-10 minutes until cheese is melted, then top with tomato and any other toppings.",
    ],
    tags: ["Beef", "Sheet-Pan", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d088",
    title: "Carnitas Tacos",
    description: "Slow cooker pork carnitas, crisped up for tender-crispy tacos.",
    ingredients: [
      "3 lb pork shoulder",
      "1 tbsp cumin",
      "1 tbsp chili powder",
      "1 orange, juiced",
      "1 cup chicken broth",
      "12 small tortillas",
    ],
    instructions: [
      "Season pork with cumin and chili powder and place in the slow cooker with orange juice and broth.",
      "Cover and cook on low 8 hours until it shreds easily.",
      "Shred the pork and, for extra-crispy edges, broil on a sheet pan 5 minutes.",
      "Serve in tortillas with your favorite toppings.",
    ],
    tags: ["Pork", "Slow-Cooker", "Tacos", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 480,
    servings: 6,
    image_url: null,
  },
  {
    id: "d089",
    title: "Chicken Tortilla Soup",
    description: "A zesty, satisfying soup topped with crispy tortilla strips.",
    ingredients: [
      "2 cups shredded cooked chicken",
      "1 can diced tomatoes",
      "1 can black beans, drained",
      "4 cups chicken broth",
      "1 tbsp chili powder",
      "Tortilla chips, for topping",
    ],
    instructions: [
      "Combine chicken, tomatoes, beans, broth, and chili powder in a large pot.",
      "Bring to a simmer and cook 15-20 minutes.",
      "Season with salt to taste.",
      "Serve topped with crushed tortilla chips, cheese, and avocado.",
    ],
    tags: ["Chicken", "Soup", "One-Pot", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 6,
    image_url: null,
  },
  {
    id: "d090",
    title: "Veggie Enchiladas",
    description: "Rolled tortillas filled with beans and veggies in enchilada sauce.",
    ingredients: [
      "1 can black beans, drained",
      "2 cups sautéed peppers and onions",
      "10 small tortillas",
      "2 cups enchilada sauce",
      "2 cups shredded cheese",
      "1 tsp cumin",
    ],
    instructions: [
      "Preheat oven to 375°F.",
      "Mix beans, sautéed vegetables, and cumin.",
      "Fill tortillas with the mixture and roll, placing seam-side down in a baking dish.",
      "Pour sauce over the top, sprinkle with cheese, and bake 20 minutes until bubbly.",
    ],
    tags: ["Vegetarian", "Mexican"],
    prep_time_minutes: 15,
    cook_time_minutes: 25,
    servings: 5,
    image_url: null,
  },
  {
    id: "d091",
    title: "Steak Quesadillas",
    description: "Sliced steak and melted cheese folded into crispy tortillas.",
    ingredients: [
      "1 lb flank steak, sliced thin",
      "2 cups shredded Mexican blend cheese",
      "8 small tortillas",
      "1 tbsp taco seasoning",
      "1 bell pepper, sliced",
      "Butter, for the pan",
    ],
    instructions: [
      "Season steak with taco seasoning and cook in a hot skillet with bell pepper until browned, about 5 minutes.",
      "Layer steak, pepper, and cheese between two tortillas.",
      "Cook in a buttered skillet 3 minutes per side until golden and cheese is melted.",
      "Slice into wedges and serve.",
    ],
    tags: ["Beef", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d092",
    title: "Chili Lime Chicken Bowls",
    description: "Zesty grilled-style chicken over rice with beans and lime.",
    ingredients: [
      "1.5 lbs chicken breast, cubed",
      "2 tbsp chili powder",
      "1 lime, juiced",
      "2 cups cooked rice",
      "1 can black beans, drained",
      "1 cup corn",
    ],
    instructions: [
      "Toss chicken with chili powder and half the lime juice.",
      "Cook chicken in a hot skillet 6-8 minutes until browned and cooked through.",
      "Divide rice among bowls and top with chicken, beans, and corn.",
      "Finish with remaining lime juice before serving.",
    ],
    tags: ["Chicken", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },

  // ---------------------------------------------------------------------
  // Grill / Sheet-Pan / One-Pot misc
  // ---------------------------------------------------------------------
  {
    id: "d093",
    title: "Grilled BBQ Chicken",
    description: "Classic barbecue chicken, sticky and charred from the grill.",
    ingredients: [
      "8 chicken drumsticks or thighs",
      "1 cup barbecue sauce",
      "1 tbsp olive oil",
      "1 tsp smoked paprika",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat grill to medium heat.",
      "Season chicken with olive oil, paprika, salt, and pepper.",
      "Grill 20-25 minutes, turning occasionally, until cooked through.",
      "Brush generously with barbecue sauce during the last 5 minutes of grilling.",
    ],
    tags: ["Chicken", "Grill", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings: 4,
    image_url: null,
  },
  {
    id: "d094",
    title: "Sheet-Pan Sausage and Veggies",
    description: "A hands-off dinner of smoked sausage and roasted seasonal vegetables.",
    ingredients: [
      "1.5 lbs smoked sausage, sliced",
      "4 cups mixed vegetables (potatoes, bell pepper, zucchini)",
      "3 tbsp olive oil",
      "1 tsp Italian seasoning",
      "1 tsp garlic powder",
    ],
    instructions: [
      "Preheat oven to 425°F.",
      "Toss sausage and vegetables with olive oil, Italian seasoning, and garlic powder on a sheet pan.",
      "Spread in a single layer and roast 25-30 minutes, stirring halfway.",
      "Serve hot.",
    ],
    tags: ["Pork", "Sheet-Pan", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings: 4,
    image_url: null,
  },
  {
    id: "d095",
    title: "One-Pot Jambalaya",
    description: "A Louisiana-style rice dish with sausage, chicken, and Cajun spice.",
    ingredients: [
      "1 lb smoked sausage, sliced",
      "1 lb chicken breast, cubed",
      "1 cup rice",
      "1 can diced tomatoes",
      "2 cups chicken broth",
      "2 tbsp Cajun seasoning",
    ],
    instructions: [
      "Brown sausage and chicken in a large pot until cooked through; set aside.",
      "Add rice, tomatoes, broth, and Cajun seasoning to the pot.",
      "Return sausage and chicken to the pot, cover, and simmer 20 minutes until rice is tender.",
      "Fluff with a fork before serving.",
    ],
    tags: ["Chicken", "Pork", "One-Pot", "American"],
    prep_time_minutes: 15,
    cook_time_minutes: 30,
    servings: 6,
    image_url: null,
  },
  {
    id: "d096",
    title: "Grilled Turkey Burgers",
    description: "Juicy, lighter burgers seasoned and grilled to perfection.",
    ingredients: [
      "1.5 lbs ground turkey",
      "1/4 cup breadcrumbs",
      "1 egg",
      "1 tsp garlic powder",
      "1 tsp onion powder",
      "4 burger buns",
    ],
    instructions: [
      "Mix ground turkey, breadcrumbs, egg, garlic powder, and onion powder; form into patties.",
      "Preheat grill to medium-high heat.",
      "Grill patties 5-6 minutes per side until cooked through (165°F internal temperature).",
      "Serve on buns with your favorite toppings.",
    ],
    tags: ["Grill", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    image_url: null,
  },
  {
    id: "d097",
    title: "Sheet-Pan Shrimp Boil",
    description: "A classic shrimp boil roasted on a sheet pan for easy cleanup.",
    ingredients: [
      "1.5 lbs shrimp, peeled and deveined",
      "1 lb baby potatoes, halved",
      "2 ears corn, cut into thirds",
      "1 lb smoked sausage, sliced",
      "3 tbsp Old Bay seasoning",
      "4 tbsp butter, melted",
    ],
    instructions: [
      "Preheat oven to 425°F.",
      "Toss potatoes and sausage with half the butter and Old Bay; roast 20 minutes on a sheet pan.",
      "Add shrimp and corn, toss with remaining butter and seasoning, and roast 10-12 more minutes.",
      "Serve hot with extra lemon wedges.",
    ],
    tags: ["Seafood", "Pork", "Sheet-Pan", "American"],
    prep_time_minutes: 15,
    cook_time_minutes: 30,
    servings: 4,
    image_url: null,
  },
  {
    id: "d098",
    title: "One-Pot Creamy Chicken and Rice",
    description: "A rich, creamy chicken and rice dinner made entirely in one pot.",
    ingredients: [
      "1.5 lbs chicken thighs, cubed",
      "1 cup rice",
      "3 cups chicken broth",
      "1 cup heavy cream",
      "1 cup frozen peas",
      "1 tsp garlic powder",
    ],
    instructions: [
      "Sear chicken in a large pot until browned; season with garlic powder.",
      "Stir in rice and broth, cover, and simmer 18-20 minutes until rice is tender.",
      "Stir in cream and peas and cook 3-4 minutes until heated through.",
      "Season with salt and pepper before serving.",
    ],
    tags: ["Chicken", "One-Pot", "American"],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings: 4,
    image_url: null,
  },
  {
    id: "d099",
    title: "Grilled Flank Steak with Chimichurri",
    description: "Simply seasoned grilled steak topped with a bright herb sauce.",
    ingredients: [
      "1.5 lbs flank steak",
      "1 cup fresh parsley, chopped",
      "3 cloves garlic, minced",
      "1/3 cup olive oil",
      "2 tbsp red wine vinegar",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Season steak generously with salt and pepper.",
      "Preheat grill to high heat and grill steak 4-5 minutes per side for medium-rare.",
      "Whisk parsley, garlic, olive oil, and vinegar together for the chimichurri.",
      "Let steak rest 5 minutes, slice against the grain, and top with chimichurri.",
    ],
    tags: ["Beef", "Grill", "Mediterranean"],
    prep_time_minutes: 15,
    cook_time_minutes: 10,
    servings: 4,
    image_url: null,
  },
  {
    id: "d100",
    title: "Sheet-Pan Fajita Bowls",
    description: "Roasted fajita vegetables and chicken served over rice for an easy bowl dinner.",
    ingredients: [
      "1.5 lbs chicken breast, sliced",
      "2 bell peppers, sliced",
      "1 onion, sliced",
      "2 tbsp fajita seasoning",
      "2 tbsp olive oil",
      "2 cups cooked rice",
    ],
    instructions: [
      "Preheat oven to 425°F.",
      "Toss chicken, peppers, and onion with olive oil and fajita seasoning on a sheet pan.",
      "Roast 18-20 minutes, stirring halfway, until chicken is cooked through.",
      "Serve over rice with your favorite toppings.",
    ],
    tags: ["Chicken", "Sheet-Pan", "Mexican"],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    image_url: null,
  },
];
